// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package role

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq     = admin.AddMenuReq
	AddMenuResp    = admin.AddMenuResp
	AddRoleReq     = admin.AddRoleReq
	AddRoleResp    = admin.AddRoleResp
	AddUserReq     = admin.AddUserReq
	AddUserResp    = admin.AddUserResp
	DeleteMenuReq  = admin.DeleteMenuReq
	DeleteMenuResp = admin.DeleteMenuResp
	DeleteRoleReq  = admin.DeleteRoleReq
	DeleteRoleResp = admin.DeleteRoleResp
	DeleteUserReq  = admin.DeleteUserReq
	DeleteUserResp = admin.DeleteUserResp
	GetMenuReq     = admin.GetMenuReq
	GetMenuResp    = admin.GetMenuResp
	LoginReq       = admin.LoginReq
	LoginResp      = admin.LoginResp
	MenuData       = admin.MenuData
	MenuListReq    = admin.MenuListReq
	MenuListResp   = admin.MenuListResp
	RefreshReq     = admin.RefreshReq
	RoleData       = admin.RoleData
	RoleListReq    = admin.RoleListReq
	RoleListResp   = admin.RoleListResp
	UpdateMenuReq  = admin.UpdateMenuReq
	UpdateMenuResp = admin.UpdateMenuResp
	UpdateRoleReq  = admin.UpdateRoleReq
	UpdateRoleResp = admin.UpdateRoleResp
	UpdateUserReq  = admin.UpdateUserReq
	UpdateUserResp = admin.UpdateUserResp
	UserData       = admin.UserData
	UserListReq    = admin.UserListReq
	UserListResp   = admin.UserListResp

	Role interface {
		AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error)
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
		RoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListResp, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.AddRole(ctx, in, opts...)
}

func (m *defaultRole) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRole) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRole) RoleList(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.RoleList(ctx, in, opts...)
}
