# Working directory
root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "tmp/auth"
# Binary file yields from `cmd`.
cmd = "go build -gcflags 'all=-N -l' -o tmp/auth apps/auth/rpc/auth.go && cp -r apps/auth/rpc/etc ."
# Customize binary, can setup environment variables when run your app.
full_bin = "dlv --listen=127.0.0.1:10001 --headless=true --api-version=2 --check-go-version=false --continue --accept-multiclient exec tmp/auth --"
delay = 1000
include_dir = []
include_ext = ["go", "tpl", "src"]
include_file = []
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
# Array of commands to run before each build
# pre_cmd = ["echo 'hello air' > pre_cmd.txt"]
# Array of commands to run after ^C
# post_cmd = ["powershell.exe Stop-Process -Id (Get-NetTCPConnection -LocalPort 12388).OwningProcess -Force"]
# post_cmd = ["echo killing the dlv process.", "powershell.exe Stop-Process -Id (Get-NetTCPConnection -LocalPort 2345).OwningProcess -Force", "echo kille success"]
follow_symlink = false
kill_delay = "0s"
log = "auth-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Show log time
time = true
# Only show main log (silences watcher, build, runner)
main_only = true
# silence all logs produced by air
silent = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
