version: "v3"

services:
  zero-admin-mysql:
    image: mysql
    container_name: zero-admin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zero-admin
    ports:
      - "3306:3306"

  zero-admin-redis:
    image: redis
    container_name: zero-admin-redis
    restart: always
    ports:
      - "6379:6379"

  zero-admin-etcd:
    image: bitnami/etcd
    container_name: zero-admin-etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
