// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: apps/customer/rpc/customer.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone          string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	TgId           string `protobuf:"bytes,3,opt,name=tgId,proto3" json:"tgId,omitempty"`
	TgUsername     string `protobuf:"bytes,4,opt,name=tgUsername,proto3" json:"tgUsername,omitempty"`
	TgFirstName    string `protobuf:"bytes,5,opt,name=tgFirstName,proto3" json:"tgFirstName,omitempty"`
	TgLastName     string `protobuf:"bytes,6,opt,name=tgLastName,proto3" json:"tgLastName,omitempty"`
	TgLanguageCode string `protobuf:"bytes,7,opt,name=tgLanguageCode,proto3" json:"tgLanguageCode,omitempty"`
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CustomerInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CustomerInfo) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *CustomerInfo) GetTgUsername() string {
	if x != nil {
		return x.TgUsername
	}
	return ""
}

func (x *CustomerInfo) GetTgFirstName() string {
	if x != nil {
		return x.TgFirstName
	}
	return ""
}

func (x *CustomerInfo) GetTgLastName() string {
	if x != nil {
		return x.TgLastName
	}
	return ""
}

func (x *CustomerInfo) GetTgLanguageCode() string {
	if x != nil {
		return x.TgLanguageCode
	}
	return ""
}

type AddCustomerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone          string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	TgId           string `protobuf:"bytes,2,opt,name=tgId,proto3" json:"tgId,omitempty"`
	TgUsername     string `protobuf:"bytes,3,opt,name=tgUsername,proto3" json:"tgUsername,omitempty"`
	TgFirstName    string `protobuf:"bytes,4,opt,name=tgFirstName,proto3" json:"tgFirstName,omitempty"`
	TgLastName     string `protobuf:"bytes,5,opt,name=tgLastName,proto3" json:"tgLastName,omitempty"`
	TgLanguageCode string `protobuf:"bytes,6,opt,name=tgLanguageCode,proto3" json:"tgLanguageCode,omitempty"`
}

func (x *AddCustomerReq) Reset() {
	*x = AddCustomerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerReq) ProtoMessage() {}

func (x *AddCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerReq.ProtoReflect.Descriptor instead.
func (*AddCustomerReq) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{1}
}

func (x *AddCustomerReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddCustomerReq) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *AddCustomerReq) GetTgUsername() string {
	if x != nil {
		return x.TgUsername
	}
	return ""
}

func (x *AddCustomerReq) GetTgFirstName() string {
	if x != nil {
		return x.TgFirstName
	}
	return ""
}

func (x *AddCustomerReq) GetTgLastName() string {
	if x != nil {
		return x.TgLastName
	}
	return ""
}

func (x *AddCustomerReq) GetTgLanguageCode() string {
	if x != nil {
		return x.TgLanguageCode
	}
	return ""
}

type DeleteCustomerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteCustomerReq) Reset() {
	*x = DeleteCustomerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerReq) ProtoMessage() {}

func (x *DeleteCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerReq.ProtoReflect.Descriptor instead.
func (*DeleteCustomerReq) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCustomerReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteCustomerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCustomerResp) Reset() {
	*x = DeleteCustomerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCustomerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerResp) ProtoMessage() {}

func (x *DeleteCustomerResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerResp.ProtoReflect.Descriptor instead.
func (*DeleteCustomerResp) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{3}
}

type GetCustomerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetCustomerReq) Reset() {
	*x = GetCustomerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerReq) ProtoMessage() {}

func (x *GetCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerReq.ProtoReflect.Descriptor instead.
func (*GetCustomerReq) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetCustomerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer []*CustomerInfo `protobuf:"bytes,1,rep,name=customer,proto3" json:"customer,omitempty"`
}

func (x *GetCustomerResp) Reset() {
	*x = GetCustomerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_customer_rpc_customer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResp) ProtoMessage() {}

func (x *GetCustomerResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_customer_rpc_customer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResp.ProtoReflect.Descriptor instead.
func (*GetCustomerResp) Descriptor() ([]byte, []int) {
	return file_apps_customer_rpc_customer_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerResp) GetCustomer() []*CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

var File_apps_customer_rpc_customer_proto protoreflect.FileDescriptor

var file_apps_customer_rpc_customer_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0xd2, 0x01, 0x0a,
	0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x67, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x67, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x67,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x67, 0x4c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x67, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x67, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x74, 0x67, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x67,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x67, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x67, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x67, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x67, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x74, 0x67, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x67, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x08,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x32, 0xa6, 0x02, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x41, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x18, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_customer_rpc_customer_proto_rawDescOnce sync.Once
	file_apps_customer_rpc_customer_proto_rawDescData = file_apps_customer_rpc_customer_proto_rawDesc
)

func file_apps_customer_rpc_customer_proto_rawDescGZIP() []byte {
	file_apps_customer_rpc_customer_proto_rawDescOnce.Do(func() {
		file_apps_customer_rpc_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_customer_rpc_customer_proto_rawDescData)
	})
	return file_apps_customer_rpc_customer_proto_rawDescData
}

var file_apps_customer_rpc_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_customer_rpc_customer_proto_goTypes = []interface{}{
	(*CustomerInfo)(nil),       // 0: customer.CustomerInfo
	(*AddCustomerReq)(nil),     // 1: customer.AddCustomerReq
	(*DeleteCustomerReq)(nil),  // 2: customer.DeleteCustomerReq
	(*DeleteCustomerResp)(nil), // 3: customer.DeleteCustomerResp
	(*GetCustomerReq)(nil),     // 4: customer.GetCustomerReq
	(*GetCustomerResp)(nil),    // 5: customer.GetCustomerResp
}
var file_apps_customer_rpc_customer_proto_depIdxs = []int32{
	0, // 0: customer.GetCustomerResp.customer:type_name -> customer.CustomerInfo
	1, // 1: customer.Customer.AddCustomer:input_type -> customer.AddCustomerReq
	0, // 2: customer.Customer.UpdateCustomer:input_type -> customer.CustomerInfo
	2, // 3: customer.Customer.DeleteCustomer:input_type -> customer.DeleteCustomerReq
	4, // 4: customer.Customer.GetCustomer:input_type -> customer.GetCustomerReq
	0, // 5: customer.Customer.AddCustomer:output_type -> customer.CustomerInfo
	0, // 6: customer.Customer.UpdateCustomer:output_type -> customer.CustomerInfo
	3, // 7: customer.Customer.DeleteCustomer:output_type -> customer.DeleteCustomerResp
	5, // 8: customer.Customer.GetCustomer:output_type -> customer.GetCustomerResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_customer_rpc_customer_proto_init() }
func file_apps_customer_rpc_customer_proto_init() {
	if File_apps_customer_rpc_customer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_customer_rpc_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_customer_rpc_customer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCustomerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_customer_rpc_customer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCustomerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_customer_rpc_customer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCustomerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_customer_rpc_customer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_customer_rpc_customer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_customer_rpc_customer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_customer_rpc_customer_proto_goTypes,
		DependencyIndexes: file_apps_customer_rpc_customer_proto_depIdxs,
		MessageInfos:      file_apps_customer_rpc_customer_proto_msgTypes,
	}.Build()
	File_apps_customer_rpc_customer_proto = out.File
	file_apps_customer_rpc_customer_proto_rawDesc = nil
	file_apps_customer_rpc_customer_proto_goTypes = nil
	file_apps_customer_rpc_customer_proto_depIdxs = nil
}
