// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysApisColumns holds the columns for the "sys_apis" table.
	SysApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeInt64, Default: 1728901115},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt8, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "path", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "creator", Type: field.TypeInt64},
		{Name: "updater", Type: field.TypeInt64},
		{Name: "deleter", Type: field.TypeInt64},
	}
	// SysApisTable holds the schema information for the "sys_apis" table.
	SysApisTable = &schema.Table{
		Name:       "sys_apis",
		Columns:    SysApisColumns,
		PrimaryKey: []*schema.Column{SysApisColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_apis_sys_users_create_by",
				Columns:    []*schema.Column{SysApisColumns[8]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_apis_sys_users_update_by",
				Columns:    []*schema.Column{SysApisColumns[9]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_apis_sys_users_delete_by",
				Columns:    []*schema.Column{SysApisColumns[10]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SysMenusColumns holds the columns for the "sys_menus" table.
	SysMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeInt64, Default: 1728901115},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt8, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "hidden", Type: field.TypeBool, Default: false},
		{Name: "creator", Type: field.TypeInt64},
		{Name: "updater", Type: field.TypeInt64},
		{Name: "deleter", Type: field.TypeInt64},
	}
	// SysMenusTable holds the schema information for the "sys_menus" table.
	SysMenusTable = &schema.Table{
		Name:       "sys_menus",
		Columns:    SysMenusColumns,
		PrimaryKey: []*schema.Column{SysMenusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_menus_sys_users_create_by",
				Columns:    []*schema.Column{SysMenusColumns[9]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_menus_sys_users_update_by",
				Columns:    []*schema.Column{SysMenusColumns[10]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_menus_sys_users_delete_by",
				Columns:    []*schema.Column{SysMenusColumns[11]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeInt64, Default: 1728901115},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt8, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "remark", Type: field.TypeString, Size: 512},
		{Name: "creator", Type: field.TypeInt64},
		{Name: "updater", Type: field.TypeInt64},
		{Name: "deleter", Type: field.TypeInt64},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_roles_sys_users_create_by",
				Columns:    []*schema.Column{SysRolesColumns[9]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_roles_sys_users_update_by",
				Columns:    []*schema.Column{SysRolesColumns[10]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_roles_sys_users_delete_by",
				Columns:    []*schema.Column{SysRolesColumns[11]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeInt64, Default: 1728901115},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt8, Default: 0},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "nickname", Type: field.TypeString, Size: 255},
		{Name: "avatar", Type: field.TypeString, Size: 255},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "remark", Type: field.TypeString, Size: 512},
		{Name: "creator", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "updater", Type: field.TypeInt64, Unique: true, Nullable: true},
		{Name: "deleter", Type: field.TypeInt64, Unique: true, Nullable: true},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_users_sys_users_create_by",
				Columns:    []*schema.Column{SysUsersColumns[12]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "sys_users_sys_users_update_by",
				Columns:    []*schema.Column{SysUsersColumns[13]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "sys_users_sys_users_delete_by",
				Columns:    []*schema.Column{SysUsersColumns[14]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysApisTable,
		SysMenusTable,
		SysRolesTable,
		SysUsersTable,
	}
)

func init() {
	SysApisTable.ForeignKeys[0].RefTable = SysUsersTable
	SysApisTable.ForeignKeys[1].RefTable = SysUsersTable
	SysApisTable.ForeignKeys[2].RefTable = SysUsersTable
	SysMenusTable.ForeignKeys[0].RefTable = SysUsersTable
	SysMenusTable.ForeignKeys[1].RefTable = SysUsersTable
	SysMenusTable.ForeignKeys[2].RefTable = SysUsersTable
	SysRolesTable.ForeignKeys[0].RefTable = SysUsersTable
	SysRolesTable.ForeignKeys[1].RefTable = SysUsersTable
	SysRolesTable.ForeignKeys[2].RefTable = SysUsersTable
	SysUsersTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUsersTable.ForeignKeys[1].RefTable = SysUsersTable
	SysUsersTable.ForeignKeys[2].RefTable = SysUsersTable
}
