// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: auth.proto

package casbin

import (
	"context"

	"xlife/apps/auth/rpc/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq      = auth.AddMenuReq
	AddMenuResp     = auth.AddMenuResp
	AddRoleReq      = auth.AddRoleReq
	AddRoleResp     = auth.AddRoleResp
	AddUserReq      = auth.AddUserReq
	AddUserResp     = auth.AddUserResp
	CasbinCheckReq  = auth.CasbinCheckReq
	CasbinCheckResp = auth.CasbinCheckResp
	DeleteMenuReq   = auth.DeleteMenuReq
	DeleteMenuResp  = auth.DeleteMenuResp
	DeleteRoleReq   = auth.DeleteRoleReq
	DeleteRoleResp  = auth.DeleteRoleResp
	DeleteUserReq   = auth.DeleteUserReq
	DeleteUserResp  = auth.DeleteUserResp
	GetMenuReq      = auth.GetMenuReq
	GetMenuResp     = auth.GetMenuResp
	LoginReq        = auth.LoginReq
	LoginResp       = auth.LoginResp
	MenuData        = auth.MenuData
	MenuListReq     = auth.MenuListReq
	MenuListResp    = auth.MenuListResp
	RefreshReq      = auth.RefreshReq
	RoleData        = auth.RoleData
	RoleListReq     = auth.RoleListReq
	RoleListResp    = auth.RoleListResp
	UpdateMenuReq   = auth.UpdateMenuReq
	UpdateMenuResp  = auth.UpdateMenuResp
	UpdateRoleReq   = auth.UpdateRoleReq
	UpdateRoleResp  = auth.UpdateRoleResp
	UpdateUserReq   = auth.UpdateUserReq
	UpdateUserResp  = auth.UpdateUserResp
	UserData        = auth.UserData
	UserListReq     = auth.UserListReq
	UserListResp    = auth.UserListResp

	Casbin interface {
		Check(ctx context.Context, in *CasbinCheckReq, opts ...grpc.CallOption) (*CasbinCheckResp, error)
	}

	defaultCasbin struct {
		cli zrpc.Client
	}
)

func NewCasbin(cli zrpc.Client) Casbin {
	return &defaultCasbin{
		cli: cli,
	}
}

func (m *defaultCasbin) Check(ctx context.Context, in *CasbinCheckReq, opts ...grpc.CallOption) (*CasbinCheckResp, error) {
	client := auth.NewCasbinClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}
