// Code generated by ent, DO NOT EDIT.

package ent

import (
	"zero-admin/ent/schema"
	"zero-admin/ent/sysapi"
	"zero-admin/ent/sysmenu"
	"zero-admin/ent/sysrole"
	"zero-admin/ent/sysuser"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysapiMixin := schema.SysApi{}.Mixin()
	sysapiMixinFields0 := sysapiMixin[0].Fields()
	_ = sysapiMixinFields0
	sysapiMixinFields1 := sysapiMixin[1].Fields()
	_ = sysapiMixinFields1
	sysapiFields := schema.SysApi{}.Fields()
	_ = sysapiFields
	// sysapiDescCreatedAt is the schema descriptor for created_at field.
	sysapiDescCreatedAt := sysapiMixinFields0[1].Descriptor()
	// sysapi.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysapi.DefaultCreatedAt = sysapiDescCreatedAt.Default.(int64)
	// sysapiDescUpdatedAt is the schema descriptor for updated_at field.
	sysapiDescUpdatedAt := sysapiMixinFields0[2].Descriptor()
	// sysapi.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysapi.UpdateDefaultUpdatedAt = sysapiDescUpdatedAt.UpdateDefault.(func() int64)
	// sysapiDescIsDeleted is the schema descriptor for is_deleted field.
	sysapiDescIsDeleted := sysapiMixinFields0[4].Descriptor()
	// sysapi.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	sysapi.DefaultIsDeleted = sysapiDescIsDeleted.Default.(bool)
	// sysapiDescSort is the schema descriptor for sort field.
	sysapiDescSort := sysapiMixinFields1[0].Descriptor()
	// sysapi.DefaultSort holds the default value on creation for the sort field.
	sysapi.DefaultSort = sysapiDescSort.Default.(int8)
	// sysapi.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysapi.SortValidator = sysapiDescSort.Validators[0].(func(int8) error)
	// sysapiDescCreator is the schema descriptor for creator field.
	sysapiDescCreator := sysapiMixinFields1[1].Descriptor()
	// sysapi.CreatorValidator is a validator for the "creator" field. It is called by the builders before save.
	sysapi.CreatorValidator = sysapiDescCreator.Validators[0].(func(int64) error)
	// sysapiDescUpdater is the schema descriptor for updater field.
	sysapiDescUpdater := sysapiMixinFields1[2].Descriptor()
	// sysapi.UpdaterValidator is a validator for the "updater" field. It is called by the builders before save.
	sysapi.UpdaterValidator = sysapiDescUpdater.Validators[0].(func(int64) error)
	// sysapiDescDeleter is the schema descriptor for deleter field.
	sysapiDescDeleter := sysapiMixinFields1[3].Descriptor()
	// sysapi.DeleterValidator is a validator for the "deleter" field. It is called by the builders before save.
	sysapi.DeleterValidator = sysapiDescDeleter.Validators[0].(func(int64) error)
	// sysapiDescName is the schema descriptor for name field.
	sysapiDescName := sysapiFields[0].Descriptor()
	// sysapi.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysapi.NameValidator = func() func(string) error {
		validators := sysapiDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysapiDescPath is the schema descriptor for path field.
	sysapiDescPath := sysapiFields[1].Descriptor()
	// sysapi.PathValidator is a validator for the "path" field. It is called by the builders before save.
	sysapi.PathValidator = func() func(string) error {
		validators := sysapiDescPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_path string) error {
			for _, fn := range fns {
				if err := fn(_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysapiDescID is the schema descriptor for id field.
	sysapiDescID := sysapiMixinFields0[0].Descriptor()
	// sysapi.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysapi.IDValidator = sysapiDescID.Validators[0].(func(int64) error)
	sysmenuMixin := schema.SysMenu{}.Mixin()
	sysmenuMixinFields0 := sysmenuMixin[0].Fields()
	_ = sysmenuMixinFields0
	sysmenuMixinFields1 := sysmenuMixin[1].Fields()
	_ = sysmenuMixinFields1
	sysmenuFields := schema.SysMenu{}.Fields()
	_ = sysmenuFields
	// sysmenuDescCreatedAt is the schema descriptor for created_at field.
	sysmenuDescCreatedAt := sysmenuMixinFields0[1].Descriptor()
	// sysmenu.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysmenu.DefaultCreatedAt = sysmenuDescCreatedAt.Default.(int64)
	// sysmenuDescUpdatedAt is the schema descriptor for updated_at field.
	sysmenuDescUpdatedAt := sysmenuMixinFields0[2].Descriptor()
	// sysmenu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysmenu.UpdateDefaultUpdatedAt = sysmenuDescUpdatedAt.UpdateDefault.(func() int64)
	// sysmenuDescIsDeleted is the schema descriptor for is_deleted field.
	sysmenuDescIsDeleted := sysmenuMixinFields0[4].Descriptor()
	// sysmenu.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	sysmenu.DefaultIsDeleted = sysmenuDescIsDeleted.Default.(bool)
	// sysmenuDescSort is the schema descriptor for sort field.
	sysmenuDescSort := sysmenuMixinFields1[0].Descriptor()
	// sysmenu.DefaultSort holds the default value on creation for the sort field.
	sysmenu.DefaultSort = sysmenuDescSort.Default.(int8)
	// sysmenu.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysmenu.SortValidator = sysmenuDescSort.Validators[0].(func(int8) error)
	// sysmenuDescCreator is the schema descriptor for creator field.
	sysmenuDescCreator := sysmenuMixinFields1[1].Descriptor()
	// sysmenu.CreatorValidator is a validator for the "creator" field. It is called by the builders before save.
	sysmenu.CreatorValidator = sysmenuDescCreator.Validators[0].(func(int64) error)
	// sysmenuDescUpdater is the schema descriptor for updater field.
	sysmenuDescUpdater := sysmenuMixinFields1[2].Descriptor()
	// sysmenu.UpdaterValidator is a validator for the "updater" field. It is called by the builders before save.
	sysmenu.UpdaterValidator = sysmenuDescUpdater.Validators[0].(func(int64) error)
	// sysmenuDescDeleter is the schema descriptor for deleter field.
	sysmenuDescDeleter := sysmenuMixinFields1[3].Descriptor()
	// sysmenu.DeleterValidator is a validator for the "deleter" field. It is called by the builders before save.
	sysmenu.DeleterValidator = sysmenuDescDeleter.Validators[0].(func(int64) error)
	// sysmenuDescName is the schema descriptor for name field.
	sysmenuDescName := sysmenuFields[0].Descriptor()
	// sysmenu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysmenu.NameValidator = func() func(string) error {
		validators := sysmenuDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysmenuDescParentID is the schema descriptor for parent_id field.
	sysmenuDescParentID := sysmenuFields[1].Descriptor()
	// sysmenu.DefaultParentID holds the default value on creation for the parent_id field.
	sysmenu.DefaultParentID = sysmenuDescParentID.Default.(int64)
	// sysmenuDescHidden is the schema descriptor for hidden field.
	sysmenuDescHidden := sysmenuFields[2].Descriptor()
	// sysmenu.DefaultHidden holds the default value on creation for the hidden field.
	sysmenu.DefaultHidden = sysmenuDescHidden.Default.(bool)
	// sysmenuDescID is the schema descriptor for id field.
	sysmenuDescID := sysmenuMixinFields0[0].Descriptor()
	// sysmenu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysmenu.IDValidator = sysmenuDescID.Validators[0].(func(int64) error)
	sysroleMixin := schema.SysRole{}.Mixin()
	sysroleMixinFields0 := sysroleMixin[0].Fields()
	_ = sysroleMixinFields0
	sysroleMixinFields1 := sysroleMixin[1].Fields()
	_ = sysroleMixinFields1
	sysroleFields := schema.SysRole{}.Fields()
	_ = sysroleFields
	// sysroleDescCreatedAt is the schema descriptor for created_at field.
	sysroleDescCreatedAt := sysroleMixinFields0[1].Descriptor()
	// sysrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysrole.DefaultCreatedAt = sysroleDescCreatedAt.Default.(int64)
	// sysroleDescUpdatedAt is the schema descriptor for updated_at field.
	sysroleDescUpdatedAt := sysroleMixinFields0[2].Descriptor()
	// sysrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysrole.UpdateDefaultUpdatedAt = sysroleDescUpdatedAt.UpdateDefault.(func() int64)
	// sysroleDescIsDeleted is the schema descriptor for is_deleted field.
	sysroleDescIsDeleted := sysroleMixinFields0[4].Descriptor()
	// sysrole.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	sysrole.DefaultIsDeleted = sysroleDescIsDeleted.Default.(bool)
	// sysroleDescSort is the schema descriptor for sort field.
	sysroleDescSort := sysroleMixinFields1[0].Descriptor()
	// sysrole.DefaultSort holds the default value on creation for the sort field.
	sysrole.DefaultSort = sysroleDescSort.Default.(int8)
	// sysrole.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysrole.SortValidator = sysroleDescSort.Validators[0].(func(int8) error)
	// sysroleDescCreator is the schema descriptor for creator field.
	sysroleDescCreator := sysroleMixinFields1[1].Descriptor()
	// sysrole.CreatorValidator is a validator for the "creator" field. It is called by the builders before save.
	sysrole.CreatorValidator = sysroleDescCreator.Validators[0].(func(int64) error)
	// sysroleDescUpdater is the schema descriptor for updater field.
	sysroleDescUpdater := sysroleMixinFields1[2].Descriptor()
	// sysrole.UpdaterValidator is a validator for the "updater" field. It is called by the builders before save.
	sysrole.UpdaterValidator = sysroleDescUpdater.Validators[0].(func(int64) error)
	// sysroleDescDeleter is the schema descriptor for deleter field.
	sysroleDescDeleter := sysroleMixinFields1[3].Descriptor()
	// sysrole.DeleterValidator is a validator for the "deleter" field. It is called by the builders before save.
	sysrole.DeleterValidator = sysroleDescDeleter.Validators[0].(func(int64) error)
	// sysroleDescName is the schema descriptor for name field.
	sysroleDescName := sysroleFields[0].Descriptor()
	// sysrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysrole.NameValidator = func() func(string) error {
		validators := sysroleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysroleDescStatus is the schema descriptor for status field.
	sysroleDescStatus := sysroleFields[1].Descriptor()
	// sysrole.DefaultStatus holds the default value on creation for the status field.
	sysrole.DefaultStatus = sysroleDescStatus.Default.(int8)
	// sysroleDescRemark is the schema descriptor for remark field.
	sysroleDescRemark := sysroleFields[2].Descriptor()
	// sysrole.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysrole.RemarkValidator = sysroleDescRemark.Validators[0].(func(string) error)
	// sysroleDescID is the schema descriptor for id field.
	sysroleDescID := sysroleMixinFields0[0].Descriptor()
	// sysrole.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysrole.IDValidator = sysroleDescID.Validators[0].(func(int64) error)
	sysuserMixin := schema.SysUser{}.Mixin()
	sysuserMixinFields0 := sysuserMixin[0].Fields()
	_ = sysuserMixinFields0
	sysuserMixinFields1 := sysuserMixin[1].Fields()
	_ = sysuserMixinFields1
	sysuserFields := schema.SysUser{}.Fields()
	_ = sysuserFields
	// sysuserDescCreatedAt is the schema descriptor for created_at field.
	sysuserDescCreatedAt := sysuserMixinFields0[1].Descriptor()
	// sysuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuser.DefaultCreatedAt = sysuserDescCreatedAt.Default.(int64)
	// sysuserDescUpdatedAt is the schema descriptor for updated_at field.
	sysuserDescUpdatedAt := sysuserMixinFields0[2].Descriptor()
	// sysuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysuser.UpdateDefaultUpdatedAt = sysuserDescUpdatedAt.UpdateDefault.(func() int64)
	// sysuserDescIsDeleted is the schema descriptor for is_deleted field.
	sysuserDescIsDeleted := sysuserMixinFields0[4].Descriptor()
	// sysuser.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	sysuser.DefaultIsDeleted = sysuserDescIsDeleted.Default.(bool)
	// sysuserDescSort is the schema descriptor for sort field.
	sysuserDescSort := sysuserMixinFields1[0].Descriptor()
	// sysuser.DefaultSort holds the default value on creation for the sort field.
	sysuser.DefaultSort = sysuserDescSort.Default.(int8)
	// sysuser.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysuser.SortValidator = sysuserDescSort.Validators[0].(func(int8) error)
	// sysuserDescCreator is the schema descriptor for creator field.
	sysuserDescCreator := sysuserMixinFields1[1].Descriptor()
	// sysuser.CreatorValidator is a validator for the "creator" field. It is called by the builders before save.
	sysuser.CreatorValidator = sysuserDescCreator.Validators[0].(func(int64) error)
	// sysuserDescUpdater is the schema descriptor for updater field.
	sysuserDescUpdater := sysuserMixinFields1[2].Descriptor()
	// sysuser.UpdaterValidator is a validator for the "updater" field. It is called by the builders before save.
	sysuser.UpdaterValidator = sysuserDescUpdater.Validators[0].(func(int64) error)
	// sysuserDescDeleter is the schema descriptor for deleter field.
	sysuserDescDeleter := sysuserMixinFields1[3].Descriptor()
	// sysuser.DeleterValidator is a validator for the "deleter" field. It is called by the builders before save.
	sysuser.DeleterValidator = sysuserDescDeleter.Validators[0].(func(int64) error)
	// sysuserDescUsername is the schema descriptor for username field.
	sysuserDescUsername := sysuserFields[0].Descriptor()
	// sysuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	sysuser.UsernameValidator = func() func(string) error {
		validators := sysuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescPassword is the schema descriptor for password field.
	sysuserDescPassword := sysuserFields[1].Descriptor()
	// sysuser.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	sysuser.PasswordValidator = func() func(string) error {
		validators := sysuserDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescNickname is the schema descriptor for nickname field.
	sysuserDescNickname := sysuserFields[2].Descriptor()
	// sysuser.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	sysuser.NicknameValidator = func() func(string) error {
		validators := sysuserDescNickname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nickname string) error {
			for _, fn := range fns {
				if err := fn(nickname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescAvatar is the schema descriptor for avatar field.
	sysuserDescAvatar := sysuserFields[3].Descriptor()
	// sysuser.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	sysuser.AvatarValidator = sysuserDescAvatar.Validators[0].(func(string) error)
	// sysuserDescStatus is the schema descriptor for status field.
	sysuserDescStatus := sysuserFields[4].Descriptor()
	// sysuser.DefaultStatus holds the default value on creation for the status field.
	sysuser.DefaultStatus = sysuserDescStatus.Default.(int8)
	// sysuserDescRemark is the schema descriptor for remark field.
	sysuserDescRemark := sysuserFields[5].Descriptor()
	// sysuser.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysuser.RemarkValidator = sysuserDescRemark.Validators[0].(func(string) error)
	// sysuserDescID is the schema descriptor for id field.
	sysuserDescID := sysuserMixinFields0[0].Descriptor()
	// sysuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysuser.IDValidator = sysuserDescID.Validators[0].(func(int64) error)
}
