// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"zero-admin/ent/predicate"
	"zero-admin/ent/sysapi"
	"zero-admin/ent/sysuser"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysApiQuery is the builder for querying SysApi entities.
type SysApiQuery struct {
	config
	ctx          *QueryContext
	order        []sysapi.OrderOption
	inters       []Interceptor
	predicates   []predicate.SysApi
	withCreateBy *SysUserQuery
	withUpdateBy *SysUserQuery
	withDeleteBy *SysUserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysApiQuery builder.
func (saq *SysApiQuery) Where(ps ...predicate.SysApi) *SysApiQuery {
	saq.predicates = append(saq.predicates, ps...)
	return saq
}

// Limit the number of records to be returned by this query.
func (saq *SysApiQuery) Limit(limit int) *SysApiQuery {
	saq.ctx.Limit = &limit
	return saq
}

// Offset to start from.
func (saq *SysApiQuery) Offset(offset int) *SysApiQuery {
	saq.ctx.Offset = &offset
	return saq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (saq *SysApiQuery) Unique(unique bool) *SysApiQuery {
	saq.ctx.Unique = &unique
	return saq
}

// Order specifies how the records should be ordered.
func (saq *SysApiQuery) Order(o ...sysapi.OrderOption) *SysApiQuery {
	saq.order = append(saq.order, o...)
	return saq
}

// QueryCreateBy chains the current query on the "create_by" edge.
func (saq *SysApiQuery) QueryCreateBy() *SysUserQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysapi.Table, sysapi.FieldID, selector),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysapi.CreateByTable, sysapi.CreateByColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdateBy chains the current query on the "update_by" edge.
func (saq *SysApiQuery) QueryUpdateBy() *SysUserQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysapi.Table, sysapi.FieldID, selector),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysapi.UpdateByTable, sysapi.UpdateByColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeleteBy chains the current query on the "delete_by" edge.
func (saq *SysApiQuery) QueryDeleteBy() *SysUserQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysapi.Table, sysapi.FieldID, selector),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysapi.DeleteByTable, sysapi.DeleteByColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SysApi entity from the query.
// Returns a *NotFoundError when no SysApi was found.
func (saq *SysApiQuery) First(ctx context.Context) (*SysApi, error) {
	nodes, err := saq.Limit(1).All(setContextOp(ctx, saq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysapi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (saq *SysApiQuery) FirstX(ctx context.Context) *SysApi {
	node, err := saq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysApi ID from the query.
// Returns a *NotFoundError when no SysApi ID was found.
func (saq *SysApiQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = saq.Limit(1).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysapi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (saq *SysApiQuery) FirstIDX(ctx context.Context) int64 {
	id, err := saq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysApi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysApi entity is found.
// Returns a *NotFoundError when no SysApi entities are found.
func (saq *SysApiQuery) Only(ctx context.Context) (*SysApi, error) {
	nodes, err := saq.Limit(2).All(setContextOp(ctx, saq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysapi.Label}
	default:
		return nil, &NotSingularError{sysapi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (saq *SysApiQuery) OnlyX(ctx context.Context) *SysApi {
	node, err := saq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysApi ID in the query.
// Returns a *NotSingularError when more than one SysApi ID is found.
// Returns a *NotFoundError when no entities are found.
func (saq *SysApiQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = saq.Limit(2).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysapi.Label}
	default:
		err = &NotSingularError{sysapi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (saq *SysApiQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := saq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysApis.
func (saq *SysApiQuery) All(ctx context.Context) ([]*SysApi, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryAll)
	if err := saq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysApi, *SysApiQuery]()
	return withInterceptors[[]*SysApi](ctx, saq, qr, saq.inters)
}

// AllX is like All, but panics if an error occurs.
func (saq *SysApiQuery) AllX(ctx context.Context) []*SysApi {
	nodes, err := saq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysApi IDs.
func (saq *SysApiQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if saq.ctx.Unique == nil && saq.path != nil {
		saq.Unique(true)
	}
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryIDs)
	if err = saq.Select(sysapi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (saq *SysApiQuery) IDsX(ctx context.Context) []int64 {
	ids, err := saq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (saq *SysApiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryCount)
	if err := saq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, saq, querierCount[*SysApiQuery](), saq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (saq *SysApiQuery) CountX(ctx context.Context) int {
	count, err := saq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (saq *SysApiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryExist)
	switch _, err := saq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (saq *SysApiQuery) ExistX(ctx context.Context) bool {
	exist, err := saq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysApiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (saq *SysApiQuery) Clone() *SysApiQuery {
	if saq == nil {
		return nil
	}
	return &SysApiQuery{
		config:       saq.config,
		ctx:          saq.ctx.Clone(),
		order:        append([]sysapi.OrderOption{}, saq.order...),
		inters:       append([]Interceptor{}, saq.inters...),
		predicates:   append([]predicate.SysApi{}, saq.predicates...),
		withCreateBy: saq.withCreateBy.Clone(),
		withUpdateBy: saq.withUpdateBy.Clone(),
		withDeleteBy: saq.withDeleteBy.Clone(),
		// clone intermediate query.
		sql:  saq.sql.Clone(),
		path: saq.path,
	}
}

// WithCreateBy tells the query-builder to eager-load the nodes that are connected to
// the "create_by" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *SysApiQuery) WithCreateBy(opts ...func(*SysUserQuery)) *SysApiQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withCreateBy = query
	return saq
}

// WithUpdateBy tells the query-builder to eager-load the nodes that are connected to
// the "update_by" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *SysApiQuery) WithUpdateBy(opts ...func(*SysUserQuery)) *SysApiQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withUpdateBy = query
	return saq
}

// WithDeleteBy tells the query-builder to eager-load the nodes that are connected to
// the "delete_by" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *SysApiQuery) WithDeleteBy(opts ...func(*SysUserQuery)) *SysApiQuery {
	query := (&SysUserClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withDeleteBy = query
	return saq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysApi.Query().
//		GroupBy(sysapi.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (saq *SysApiQuery) GroupBy(field string, fields ...string) *SysApiGroupBy {
	saq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysApiGroupBy{build: saq}
	grbuild.flds = &saq.ctx.Fields
	grbuild.label = sysapi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.SysApi.Query().
//		Select(sysapi.FieldCreatedAt).
//		Scan(ctx, &v)
func (saq *SysApiQuery) Select(fields ...string) *SysApiSelect {
	saq.ctx.Fields = append(saq.ctx.Fields, fields...)
	sbuild := &SysApiSelect{SysApiQuery: saq}
	sbuild.label = sysapi.Label
	sbuild.flds, sbuild.scan = &saq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysApiSelect configured with the given aggregations.
func (saq *SysApiQuery) Aggregate(fns ...AggregateFunc) *SysApiSelect {
	return saq.Select().Aggregate(fns...)
}

func (saq *SysApiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range saq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, saq); err != nil {
				return err
			}
		}
	}
	for _, f := range saq.ctx.Fields {
		if !sysapi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if saq.path != nil {
		prev, err := saq.path(ctx)
		if err != nil {
			return err
		}
		saq.sql = prev
	}
	return nil
}

func (saq *SysApiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysApi, error) {
	var (
		nodes       = []*SysApi{}
		_spec       = saq.querySpec()
		loadedTypes = [3]bool{
			saq.withCreateBy != nil,
			saq.withUpdateBy != nil,
			saq.withDeleteBy != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysApi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysApi{config: saq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, saq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := saq.withCreateBy; query != nil {
		if err := saq.loadCreateBy(ctx, query, nodes, nil,
			func(n *SysApi, e *SysUser) { n.Edges.CreateBy = e }); err != nil {
			return nil, err
		}
	}
	if query := saq.withUpdateBy; query != nil {
		if err := saq.loadUpdateBy(ctx, query, nodes, nil,
			func(n *SysApi, e *SysUser) { n.Edges.UpdateBy = e }); err != nil {
			return nil, err
		}
	}
	if query := saq.withDeleteBy; query != nil {
		if err := saq.loadDeleteBy(ctx, query, nodes, nil,
			func(n *SysApi, e *SysUser) { n.Edges.DeleteBy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (saq *SysApiQuery) loadCreateBy(ctx context.Context, query *SysUserQuery, nodes []*SysApi, init func(*SysApi), assign func(*SysApi, *SysUser)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SysApi)
	for i := range nodes {
		fk := nodes[i].Creator
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "creator" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (saq *SysApiQuery) loadUpdateBy(ctx context.Context, query *SysUserQuery, nodes []*SysApi, init func(*SysApi), assign func(*SysApi, *SysUser)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SysApi)
	for i := range nodes {
		fk := nodes[i].Updater
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "updater" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (saq *SysApiQuery) loadDeleteBy(ctx context.Context, query *SysUserQuery, nodes []*SysApi, init func(*SysApi), assign func(*SysApi, *SysUser)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SysApi)
	for i := range nodes {
		fk := nodes[i].Deleter
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deleter" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (saq *SysApiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := saq.querySpec()
	_spec.Node.Columns = saq.ctx.Fields
	if len(saq.ctx.Fields) > 0 {
		_spec.Unique = saq.ctx.Unique != nil && *saq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, saq.driver, _spec)
}

func (saq *SysApiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysapi.Table, sysapi.Columns, sqlgraph.NewFieldSpec(sysapi.FieldID, field.TypeInt64))
	_spec.From = saq.sql
	if unique := saq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if saq.path != nil {
		_spec.Unique = true
	}
	if fields := saq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysapi.FieldID)
		for i := range fields {
			if fields[i] != sysapi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if saq.withCreateBy != nil {
			_spec.Node.AddColumnOnce(sysapi.FieldCreator)
		}
		if saq.withUpdateBy != nil {
			_spec.Node.AddColumnOnce(sysapi.FieldUpdater)
		}
		if saq.withDeleteBy != nil {
			_spec.Node.AddColumnOnce(sysapi.FieldDeleter)
		}
	}
	if ps := saq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := saq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := saq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := saq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (saq *SysApiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(saq.driver.Dialect())
	t1 := builder.Table(sysapi.Table)
	columns := saq.ctx.Fields
	if len(columns) == 0 {
		columns = sysapi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if saq.sql != nil {
		selector = saq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if saq.ctx.Unique != nil && *saq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range saq.predicates {
		p(selector)
	}
	for _, p := range saq.order {
		p(selector)
	}
	if offset := saq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := saq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysApiGroupBy is the group-by builder for SysApi entities.
type SysApiGroupBy struct {
	selector
	build *SysApiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sagb *SysApiGroupBy) Aggregate(fns ...AggregateFunc) *SysApiGroupBy {
	sagb.fns = append(sagb.fns, fns...)
	return sagb
}

// Scan applies the selector query and scans the result into the given value.
func (sagb *SysApiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sagb.build.ctx, ent.OpQueryGroupBy)
	if err := sagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysApiQuery, *SysApiGroupBy](ctx, sagb.build, sagb, sagb.build.inters, v)
}

func (sagb *SysApiGroupBy) sqlScan(ctx context.Context, root *SysApiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sagb.fns))
	for _, fn := range sagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sagb.flds)+len(sagb.fns))
		for _, f := range *sagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysApiSelect is the builder for selecting fields of SysApi entities.
type SysApiSelect struct {
	*SysApiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sas *SysApiSelect) Aggregate(fns ...AggregateFunc) *SysApiSelect {
	sas.fns = append(sas.fns, fns...)
	return sas
}

// Scan applies the selector query and scans the result into the given value.
func (sas *SysApiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sas.ctx, ent.OpQuerySelect)
	if err := sas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysApiQuery, *SysApiSelect](ctx, sas.SysApiQuery, sas, sas.inters, v)
}

func (sas *SysApiSelect) sqlScan(ctx context.Context, root *SysApiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sas.fns))
	for _, fn := range sas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
