// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"zero-admin/ent/sysapi"
	"zero-admin/ent/sysuser"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysApi is the model entity for the SysApi schema.
type SysApi struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int64 `json:"deleted_at,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int8 `json:"sort,omitempty"`
	// Creator holds the value of the "creator" field.
	Creator int64 `json:"creator,omitempty"`
	// Updater holds the value of the "updater" field.
	Updater int64 `json:"updater,omitempty"`
	// Deleter holds the value of the "deleter" field.
	Deleter int64 `json:"deleter,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysApiQuery when eager-loading is set.
	Edges        SysApiEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysApiEdges holds the relations/edges for other nodes in the graph.
type SysApiEdges struct {
	// CreateBy holds the value of the create_by edge.
	CreateBy *SysUser `json:"create_by,omitempty"`
	// UpdateBy holds the value of the update_by edge.
	UpdateBy *SysUser `json:"update_by,omitempty"`
	// DeleteBy holds the value of the delete_by edge.
	DeleteBy *SysUser `json:"delete_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreateByOrErr returns the CreateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysApiEdges) CreateByOrErr() (*SysUser, error) {
	if e.CreateBy != nil {
		return e.CreateBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "create_by"}
}

// UpdateByOrErr returns the UpdateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysApiEdges) UpdateByOrErr() (*SysUser, error) {
	if e.UpdateBy != nil {
		return e.UpdateBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "update_by"}
}

// DeleteByOrErr returns the DeleteBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysApiEdges) DeleteByOrErr() (*SysUser, error) {
	if e.DeleteBy != nil {
		return e.DeleteBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "delete_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysApi) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysapi.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case sysapi.FieldID, sysapi.FieldCreatedAt, sysapi.FieldUpdatedAt, sysapi.FieldDeletedAt, sysapi.FieldSort, sysapi.FieldCreator, sysapi.FieldUpdater, sysapi.FieldDeleter:
			values[i] = new(sql.NullInt64)
		case sysapi.FieldName, sysapi.FieldPath:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysApi fields.
func (sa *SysApi) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysapi.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sa.ID = int64(value.Int64)
		case sysapi.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sa.CreatedAt = value.Int64
			}
		case sysapi.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sa.UpdatedAt = value.Int64
			}
		case sysapi.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				sa.DeletedAt = value.Int64
			}
		case sysapi.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				sa.IsDeleted = value.Bool
			}
		case sysapi.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				sa.Sort = int8(value.Int64)
			}
		case sysapi.FieldCreator:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator", values[i])
			} else if value.Valid {
				sa.Creator = value.Int64
			}
		case sysapi.FieldUpdater:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updater", values[i])
			} else if value.Valid {
				sa.Updater = value.Int64
			}
		case sysapi.FieldDeleter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleter", values[i])
			} else if value.Valid {
				sa.Deleter = value.Int64
			}
		case sysapi.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sa.Name = value.String
			}
		case sysapi.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				sa.Path = value.String
			}
		default:
			sa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysApi.
// This includes values selected through modifiers, order, etc.
func (sa *SysApi) Value(name string) (ent.Value, error) {
	return sa.selectValues.Get(name)
}

// QueryCreateBy queries the "create_by" edge of the SysApi entity.
func (sa *SysApi) QueryCreateBy() *SysUserQuery {
	return NewSysApiClient(sa.config).QueryCreateBy(sa)
}

// QueryUpdateBy queries the "update_by" edge of the SysApi entity.
func (sa *SysApi) QueryUpdateBy() *SysUserQuery {
	return NewSysApiClient(sa.config).QueryUpdateBy(sa)
}

// QueryDeleteBy queries the "delete_by" edge of the SysApi entity.
func (sa *SysApi) QueryDeleteBy() *SysUserQuery {
	return NewSysApiClient(sa.config).QueryDeleteBy(sa)
}

// Update returns a builder for updating this SysApi.
// Note that you need to call SysApi.Unwrap() before calling this method if this SysApi
// was returned from a transaction, and the transaction was committed or rolled back.
func (sa *SysApi) Update() *SysApiUpdateOne {
	return NewSysApiClient(sa.config).UpdateOne(sa)
}

// Unwrap unwraps the SysApi entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sa *SysApi) Unwrap() *SysApi {
	_tx, ok := sa.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysApi is not a transactional entity")
	}
	sa.config.driver = _tx.drv
	return sa
}

// String implements the fmt.Stringer.
func (sa *SysApi) String() string {
	var builder strings.Builder
	builder.WriteString("SysApi(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sa.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", sa.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", sa.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", sa.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", sa.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", sa.Sort))
	builder.WriteString(", ")
	builder.WriteString("creator=")
	builder.WriteString(fmt.Sprintf("%v", sa.Creator))
	builder.WriteString(", ")
	builder.WriteString("updater=")
	builder.WriteString(fmt.Sprintf("%v", sa.Updater))
	builder.WriteString(", ")
	builder.WriteString("deleter=")
	builder.WriteString(fmt.Sprintf("%v", sa.Deleter))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(sa.Name)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(sa.Path)
	builder.WriteByte(')')
	return builder.String()
}

// SysApis is a parsable slice of SysApi.
type SysApis []*SysApi
