// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"zero-admin/ent/predicate"
	"zero-admin/ent/sysapi"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysApiDelete is the builder for deleting a SysApi entity.
type SysApiDelete struct {
	config
	hooks    []Hook
	mutation *SysApiMutation
}

// Where appends a list predicates to the SysApiDelete builder.
func (sad *SysApiDelete) Where(ps ...predicate.SysApi) *SysApiDelete {
	sad.mutation.Where(ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *SysApiDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sad.sqlExec, sad.mutation, sad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *SysApiDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *SysApiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sysapi.Table, sqlgraph.NewFieldSpec(sysapi.FieldID, field.TypeInt64))
	if ps := sad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sad.mutation.done = true
	return affected, err
}

// SysApiDeleteOne is the builder for deleting a single SysApi entity.
type SysApiDeleteOne struct {
	sad *SysApiDelete
}

// Where appends a list predicates to the SysApiDelete builder.
func (sado *SysApiDeleteOne) Where(ps ...predicate.SysApi) *SysApiDeleteOne {
	sado.sad.mutation.Where(ps...)
	return sado
}

// Exec executes the deletion query.
func (sado *SysApiDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sysapi.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *SysApiDeleteOne) ExecX(ctx context.Context) {
	if err := sado.Exec(ctx); err != nil {
		panic(err)
	}
}
