// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"zero-admin/ent/sysmenu"
	"zero-admin/ent/sysuser"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysMenu is the model entity for the SysMenu schema.
type SysMenu struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int64 `json:"deleted_at,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int8 `json:"sort,omitempty"`
	// Creator holds the value of the "creator" field.
	Creator int64 `json:"creator,omitempty"`
	// Updater holds the value of the "updater" field.
	Updater int64 `json:"updater,omitempty"`
	// Deleter holds the value of the "deleter" field.
	Deleter int64 `json:"deleter,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID int64 `json:"parent_id,omitempty"`
	// Hidden holds the value of the "hidden" field.
	Hidden bool `json:"hidden,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysMenuQuery when eager-loading is set.
	Edges        SysMenuEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysMenuEdges holds the relations/edges for other nodes in the graph.
type SysMenuEdges struct {
	// CreateBy holds the value of the create_by edge.
	CreateBy *SysUser `json:"create_by,omitempty"`
	// UpdateBy holds the value of the update_by edge.
	UpdateBy *SysUser `json:"update_by,omitempty"`
	// DeleteBy holds the value of the delete_by edge.
	DeleteBy *SysUser `json:"delete_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreateByOrErr returns the CreateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysMenuEdges) CreateByOrErr() (*SysUser, error) {
	if e.CreateBy != nil {
		return e.CreateBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "create_by"}
}

// UpdateByOrErr returns the UpdateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysMenuEdges) UpdateByOrErr() (*SysUser, error) {
	if e.UpdateBy != nil {
		return e.UpdateBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "update_by"}
}

// DeleteByOrErr returns the DeleteBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysMenuEdges) DeleteByOrErr() (*SysUser, error) {
	if e.DeleteBy != nil {
		return e.DeleteBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "delete_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysMenu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysmenu.FieldIsDeleted, sysmenu.FieldHidden:
			values[i] = new(sql.NullBool)
		case sysmenu.FieldID, sysmenu.FieldCreatedAt, sysmenu.FieldUpdatedAt, sysmenu.FieldDeletedAt, sysmenu.FieldSort, sysmenu.FieldCreator, sysmenu.FieldUpdater, sysmenu.FieldDeleter, sysmenu.FieldParentID:
			values[i] = new(sql.NullInt64)
		case sysmenu.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysMenu fields.
func (sm *SysMenu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysmenu.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sm.ID = int64(value.Int64)
		case sysmenu.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sm.CreatedAt = value.Int64
			}
		case sysmenu.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sm.UpdatedAt = value.Int64
			}
		case sysmenu.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				sm.DeletedAt = value.Int64
			}
		case sysmenu.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				sm.IsDeleted = value.Bool
			}
		case sysmenu.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				sm.Sort = int8(value.Int64)
			}
		case sysmenu.FieldCreator:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator", values[i])
			} else if value.Valid {
				sm.Creator = value.Int64
			}
		case sysmenu.FieldUpdater:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updater", values[i])
			} else if value.Valid {
				sm.Updater = value.Int64
			}
		case sysmenu.FieldDeleter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleter", values[i])
			} else if value.Valid {
				sm.Deleter = value.Int64
			}
		case sysmenu.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sm.Name = value.String
			}
		case sysmenu.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				sm.ParentID = value.Int64
			}
		case sysmenu.FieldHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hidden", values[i])
			} else if value.Valid {
				sm.Hidden = value.Bool
			}
		default:
			sm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysMenu.
// This includes values selected through modifiers, order, etc.
func (sm *SysMenu) Value(name string) (ent.Value, error) {
	return sm.selectValues.Get(name)
}

// QueryCreateBy queries the "create_by" edge of the SysMenu entity.
func (sm *SysMenu) QueryCreateBy() *SysUserQuery {
	return NewSysMenuClient(sm.config).QueryCreateBy(sm)
}

// QueryUpdateBy queries the "update_by" edge of the SysMenu entity.
func (sm *SysMenu) QueryUpdateBy() *SysUserQuery {
	return NewSysMenuClient(sm.config).QueryUpdateBy(sm)
}

// QueryDeleteBy queries the "delete_by" edge of the SysMenu entity.
func (sm *SysMenu) QueryDeleteBy() *SysUserQuery {
	return NewSysMenuClient(sm.config).QueryDeleteBy(sm)
}

// Update returns a builder for updating this SysMenu.
// Note that you need to call SysMenu.Unwrap() before calling this method if this SysMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (sm *SysMenu) Update() *SysMenuUpdateOne {
	return NewSysMenuClient(sm.config).UpdateOne(sm)
}

// Unwrap unwraps the SysMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sm *SysMenu) Unwrap() *SysMenu {
	_tx, ok := sm.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysMenu is not a transactional entity")
	}
	sm.config.driver = _tx.drv
	return sm
}

// String implements the fmt.Stringer.
func (sm *SysMenu) String() string {
	var builder strings.Builder
	builder.WriteString("SysMenu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", sm.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", sm.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", sm.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", sm.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", sm.Sort))
	builder.WriteString(", ")
	builder.WriteString("creator=")
	builder.WriteString(fmt.Sprintf("%v", sm.Creator))
	builder.WriteString(", ")
	builder.WriteString("updater=")
	builder.WriteString(fmt.Sprintf("%v", sm.Updater))
	builder.WriteString(", ")
	builder.WriteString("deleter=")
	builder.WriteString(fmt.Sprintf("%v", sm.Deleter))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(sm.Name)
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.ParentID))
	builder.WriteString(", ")
	builder.WriteString("hidden=")
	builder.WriteString(fmt.Sprintf("%v", sm.Hidden))
	builder.WriteByte(')')
	return builder.String()
}

// SysMenus is a parsable slice of SysMenu.
type SysMenus []*SysMenu
