// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"zero-admin/ent/sysrole"
	"zero-admin/ent/sysuser"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysRole is the model entity for the SysRole schema.
type SysRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int64 `json:"deleted_at,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int8 `json:"sort,omitempty"`
	// Creator holds the value of the "creator" field.
	Creator int64 `json:"creator,omitempty"`
	// Updater holds the value of the "updater" field.
	Updater int64 `json:"updater,omitempty"`
	// Deleter holds the value of the "deleter" field.
	Deleter int64 `json:"deleter,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysRoleQuery when eager-loading is set.
	Edges        SysRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysRoleEdges holds the relations/edges for other nodes in the graph.
type SysRoleEdges struct {
	// CreateBy holds the value of the create_by edge.
	CreateBy *SysUser `json:"create_by,omitempty"`
	// UpdateBy holds the value of the update_by edge.
	UpdateBy *SysUser `json:"update_by,omitempty"`
	// DeleteBy holds the value of the delete_by edge.
	DeleteBy *SysUser `json:"delete_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreateByOrErr returns the CreateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRoleEdges) CreateByOrErr() (*SysUser, error) {
	if e.CreateBy != nil {
		return e.CreateBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "create_by"}
}

// UpdateByOrErr returns the UpdateBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRoleEdges) UpdateByOrErr() (*SysUser, error) {
	if e.UpdateBy != nil {
		return e.UpdateBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "update_by"}
}

// DeleteByOrErr returns the DeleteBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRoleEdges) DeleteByOrErr() (*SysUser, error) {
	if e.DeleteBy != nil {
		return e.DeleteBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "delete_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case sysrole.FieldID, sysrole.FieldCreatedAt, sysrole.FieldUpdatedAt, sysrole.FieldDeletedAt, sysrole.FieldSort, sysrole.FieldCreator, sysrole.FieldUpdater, sysrole.FieldDeleter, sysrole.FieldStatus:
			values[i] = new(sql.NullInt64)
		case sysrole.FieldName, sysrole.FieldRemark:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRole fields.
func (sr *SysRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sr.ID = int64(value.Int64)
		case sysrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sr.CreatedAt = value.Int64
			}
		case sysrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sr.UpdatedAt = value.Int64
			}
		case sysrole.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				sr.DeletedAt = value.Int64
			}
		case sysrole.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				sr.IsDeleted = value.Bool
			}
		case sysrole.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				sr.Sort = int8(value.Int64)
			}
		case sysrole.FieldCreator:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator", values[i])
			} else if value.Valid {
				sr.Creator = value.Int64
			}
		case sysrole.FieldUpdater:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updater", values[i])
			} else if value.Valid {
				sr.Updater = value.Int64
			}
		case sysrole.FieldDeleter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleter", values[i])
			} else if value.Valid {
				sr.Deleter = value.Int64
			}
		case sysrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sr.Name = value.String
			}
		case sysrole.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				sr.Status = int8(value.Int64)
			}
		case sysrole.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				sr.Remark = value.String
			}
		default:
			sr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRole.
// This includes values selected through modifiers, order, etc.
func (sr *SysRole) Value(name string) (ent.Value, error) {
	return sr.selectValues.Get(name)
}

// QueryCreateBy queries the "create_by" edge of the SysRole entity.
func (sr *SysRole) QueryCreateBy() *SysUserQuery {
	return NewSysRoleClient(sr.config).QueryCreateBy(sr)
}

// QueryUpdateBy queries the "update_by" edge of the SysRole entity.
func (sr *SysRole) QueryUpdateBy() *SysUserQuery {
	return NewSysRoleClient(sr.config).QueryUpdateBy(sr)
}

// QueryDeleteBy queries the "delete_by" edge of the SysRole entity.
func (sr *SysRole) QueryDeleteBy() *SysUserQuery {
	return NewSysRoleClient(sr.config).QueryDeleteBy(sr)
}

// Update returns a builder for updating this SysRole.
// Note that you need to call SysRole.Unwrap() before calling this method if this SysRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (sr *SysRole) Update() *SysRoleUpdateOne {
	return NewSysRoleClient(sr.config).UpdateOne(sr)
}

// Unwrap unwraps the SysRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sr *SysRole) Unwrap() *SysRole {
	_tx, ok := sr.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysRole is not a transactional entity")
	}
	sr.config.driver = _tx.drv
	return sr
}

// String implements the fmt.Stringer.
func (sr *SysRole) String() string {
	var builder strings.Builder
	builder.WriteString("SysRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sr.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", sr.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", sr.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", sr.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", sr.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", sr.Sort))
	builder.WriteString(", ")
	builder.WriteString("creator=")
	builder.WriteString(fmt.Sprintf("%v", sr.Creator))
	builder.WriteString(", ")
	builder.WriteString("updater=")
	builder.WriteString(fmt.Sprintf("%v", sr.Updater))
	builder.WriteString(", ")
	builder.WriteString("deleter=")
	builder.WriteString(fmt.Sprintf("%v", sr.Deleter))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(sr.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", sr.Status))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(sr.Remark)
	builder.WriteByte(')')
	return builder.String()
}

// SysRoles is a parsable slice of SysRole.
type SysRoles []*SysRole
