// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"zero-admin/ent/sysrole"
	"zero-admin/ent/sysuser"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysRoleCreate is the builder for creating a SysRole entity.
type SysRoleCreate struct {
	config
	mutation *SysRoleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (src *SysRoleCreate) SetCreatedAt(i int64) *SysRoleCreate {
	src.mutation.SetCreatedAt(i)
	return src
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (src *SysRoleCreate) SetNillableCreatedAt(i *int64) *SysRoleCreate {
	if i != nil {
		src.SetCreatedAt(*i)
	}
	return src
}

// SetUpdatedAt sets the "updated_at" field.
func (src *SysRoleCreate) SetUpdatedAt(i int64) *SysRoleCreate {
	src.mutation.SetUpdatedAt(i)
	return src
}

// SetDeletedAt sets the "deleted_at" field.
func (src *SysRoleCreate) SetDeletedAt(i int64) *SysRoleCreate {
	src.mutation.SetDeletedAt(i)
	return src
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (src *SysRoleCreate) SetNillableDeletedAt(i *int64) *SysRoleCreate {
	if i != nil {
		src.SetDeletedAt(*i)
	}
	return src
}

// SetIsDeleted sets the "is_deleted" field.
func (src *SysRoleCreate) SetIsDeleted(b bool) *SysRoleCreate {
	src.mutation.SetIsDeleted(b)
	return src
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (src *SysRoleCreate) SetNillableIsDeleted(b *bool) *SysRoleCreate {
	if b != nil {
		src.SetIsDeleted(*b)
	}
	return src
}

// SetSort sets the "sort" field.
func (src *SysRoleCreate) SetSort(i int8) *SysRoleCreate {
	src.mutation.SetSort(i)
	return src
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (src *SysRoleCreate) SetNillableSort(i *int8) *SysRoleCreate {
	if i != nil {
		src.SetSort(*i)
	}
	return src
}

// SetCreator sets the "creator" field.
func (src *SysRoleCreate) SetCreator(i int64) *SysRoleCreate {
	src.mutation.SetCreator(i)
	return src
}

// SetUpdater sets the "updater" field.
func (src *SysRoleCreate) SetUpdater(i int64) *SysRoleCreate {
	src.mutation.SetUpdater(i)
	return src
}

// SetDeleter sets the "deleter" field.
func (src *SysRoleCreate) SetDeleter(i int64) *SysRoleCreate {
	src.mutation.SetDeleter(i)
	return src
}

// SetName sets the "name" field.
func (src *SysRoleCreate) SetName(s string) *SysRoleCreate {
	src.mutation.SetName(s)
	return src
}

// SetStatus sets the "status" field.
func (src *SysRoleCreate) SetStatus(i int8) *SysRoleCreate {
	src.mutation.SetStatus(i)
	return src
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (src *SysRoleCreate) SetNillableStatus(i *int8) *SysRoleCreate {
	if i != nil {
		src.SetStatus(*i)
	}
	return src
}

// SetRemark sets the "remark" field.
func (src *SysRoleCreate) SetRemark(s string) *SysRoleCreate {
	src.mutation.SetRemark(s)
	return src
}

// SetID sets the "id" field.
func (src *SysRoleCreate) SetID(i int64) *SysRoleCreate {
	src.mutation.SetID(i)
	return src
}

// SetCreateByID sets the "create_by" edge to the SysUser entity by ID.
func (src *SysRoleCreate) SetCreateByID(id int64) *SysRoleCreate {
	src.mutation.SetCreateByID(id)
	return src
}

// SetCreateBy sets the "create_by" edge to the SysUser entity.
func (src *SysRoleCreate) SetCreateBy(s *SysUser) *SysRoleCreate {
	return src.SetCreateByID(s.ID)
}

// SetUpdateByID sets the "update_by" edge to the SysUser entity by ID.
func (src *SysRoleCreate) SetUpdateByID(id int64) *SysRoleCreate {
	src.mutation.SetUpdateByID(id)
	return src
}

// SetUpdateBy sets the "update_by" edge to the SysUser entity.
func (src *SysRoleCreate) SetUpdateBy(s *SysUser) *SysRoleCreate {
	return src.SetUpdateByID(s.ID)
}

// SetDeleteByID sets the "delete_by" edge to the SysUser entity by ID.
func (src *SysRoleCreate) SetDeleteByID(id int64) *SysRoleCreate {
	src.mutation.SetDeleteByID(id)
	return src
}

// SetDeleteBy sets the "delete_by" edge to the SysUser entity.
func (src *SysRoleCreate) SetDeleteBy(s *SysUser) *SysRoleCreate {
	return src.SetDeleteByID(s.ID)
}

// Mutation returns the SysRoleMutation object of the builder.
func (src *SysRoleCreate) Mutation() *SysRoleMutation {
	return src.mutation
}

// Save creates the SysRole in the database.
func (src *SysRoleCreate) Save(ctx context.Context) (*SysRole, error) {
	src.defaults()
	return withHooks(ctx, src.sqlSave, src.mutation, src.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (src *SysRoleCreate) SaveX(ctx context.Context) *SysRole {
	v, err := src.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (src *SysRoleCreate) Exec(ctx context.Context) error {
	_, err := src.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (src *SysRoleCreate) ExecX(ctx context.Context) {
	if err := src.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (src *SysRoleCreate) defaults() {
	if _, ok := src.mutation.CreatedAt(); !ok {
		v := sysrole.DefaultCreatedAt
		src.mutation.SetCreatedAt(v)
	}
	if _, ok := src.mutation.IsDeleted(); !ok {
		v := sysrole.DefaultIsDeleted
		src.mutation.SetIsDeleted(v)
	}
	if _, ok := src.mutation.Sort(); !ok {
		v := sysrole.DefaultSort
		src.mutation.SetSort(v)
	}
	if _, ok := src.mutation.Status(); !ok {
		v := sysrole.DefaultStatus
		src.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (src *SysRoleCreate) check() error {
	if _, ok := src.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysRole.created_at"`)}
	}
	if _, ok := src.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysRole.updated_at"`)}
	}
	if _, ok := src.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "SysRole.is_deleted"`)}
	}
	if _, ok := src.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "SysRole.sort"`)}
	}
	if v, ok := src.mutation.Sort(); ok {
		if err := sysrole.SortValidator(v); err != nil {
			return &ValidationError{Name: "sort", err: fmt.Errorf(`ent: validator failed for field "SysRole.sort": %w`, err)}
		}
	}
	if _, ok := src.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required field "SysRole.creator"`)}
	}
	if v, ok := src.mutation.Creator(); ok {
		if err := sysrole.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`ent: validator failed for field "SysRole.creator": %w`, err)}
		}
	}
	if _, ok := src.mutation.Updater(); !ok {
		return &ValidationError{Name: "updater", err: errors.New(`ent: missing required field "SysRole.updater"`)}
	}
	if v, ok := src.mutation.Updater(); ok {
		if err := sysrole.UpdaterValidator(v); err != nil {
			return &ValidationError{Name: "updater", err: fmt.Errorf(`ent: validator failed for field "SysRole.updater": %w`, err)}
		}
	}
	if _, ok := src.mutation.Deleter(); !ok {
		return &ValidationError{Name: "deleter", err: errors.New(`ent: missing required field "SysRole.deleter"`)}
	}
	if v, ok := src.mutation.Deleter(); ok {
		if err := sysrole.DeleterValidator(v); err != nil {
			return &ValidationError{Name: "deleter", err: fmt.Errorf(`ent: validator failed for field "SysRole.deleter": %w`, err)}
		}
	}
	if _, ok := src.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysRole.name"`)}
	}
	if v, ok := src.mutation.Name(); ok {
		if err := sysrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysRole.name": %w`, err)}
		}
	}
	if _, ok := src.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysRole.status"`)}
	}
	if _, ok := src.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "SysRole.remark"`)}
	}
	if v, ok := src.mutation.Remark(); ok {
		if err := sysrole.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysRole.remark": %w`, err)}
		}
	}
	if v, ok := src.mutation.ID(); ok {
		if err := sysrole.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysRole.id": %w`, err)}
		}
	}
	if len(src.mutation.CreateByIDs()) == 0 {
		return &ValidationError{Name: "create_by", err: errors.New(`ent: missing required edge "SysRole.create_by"`)}
	}
	if len(src.mutation.UpdateByIDs()) == 0 {
		return &ValidationError{Name: "update_by", err: errors.New(`ent: missing required edge "SysRole.update_by"`)}
	}
	if len(src.mutation.DeleteByIDs()) == 0 {
		return &ValidationError{Name: "delete_by", err: errors.New(`ent: missing required edge "SysRole.delete_by"`)}
	}
	return nil
}

func (src *SysRoleCreate) sqlSave(ctx context.Context) (*SysRole, error) {
	if err := src.check(); err != nil {
		return nil, err
	}
	_node, _spec := src.createSpec()
	if err := sqlgraph.CreateNode(ctx, src.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	src.mutation.id = &_node.ID
	src.mutation.done = true
	return _node, nil
}

func (src *SysRoleCreate) createSpec() (*SysRole, *sqlgraph.CreateSpec) {
	var (
		_node = &SysRole{config: src.config}
		_spec = sqlgraph.NewCreateSpec(sysrole.Table, sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64))
	)
	if id, ok := src.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := src.mutation.CreatedAt(); ok {
		_spec.SetField(sysrole.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := src.mutation.UpdatedAt(); ok {
		_spec.SetField(sysrole.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := src.mutation.DeletedAt(); ok {
		_spec.SetField(sysrole.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = value
	}
	if value, ok := src.mutation.IsDeleted(); ok {
		_spec.SetField(sysrole.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := src.mutation.Sort(); ok {
		_spec.SetField(sysrole.FieldSort, field.TypeInt8, value)
		_node.Sort = value
	}
	if value, ok := src.mutation.Name(); ok {
		_spec.SetField(sysrole.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := src.mutation.Status(); ok {
		_spec.SetField(sysrole.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := src.mutation.Remark(); ok {
		_spec.SetField(sysrole.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if nodes := src.mutation.CreateByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sysrole.CreateByTable,
			Columns: []string{sysrole.CreateByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.Creator = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := src.mutation.UpdateByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sysrole.UpdateByTable,
			Columns: []string{sysrole.UpdateByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.Updater = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := src.mutation.DeleteByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sysrole.DeleteByTable,
			Columns: []string{sysrole.DeleteByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.Deleter = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysRoleCreateBulk is the builder for creating many SysRole entities in bulk.
type SysRoleCreateBulk struct {
	config
	err      error
	builders []*SysRoleCreate
}

// Save creates the SysRole entities in the database.
func (srcb *SysRoleCreateBulk) Save(ctx context.Context) ([]*SysRole, error) {
	if srcb.err != nil {
		return nil, srcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(srcb.builders))
	nodes := make([]*SysRole, len(srcb.builders))
	mutators := make([]Mutator, len(srcb.builders))
	for i := range srcb.builders {
		func(i int, root context.Context) {
			builder := srcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, srcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, srcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, srcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (srcb *SysRoleCreateBulk) SaveX(ctx context.Context) []*SysRole {
	v, err := srcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (srcb *SysRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := srcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (srcb *SysRoleCreateBulk) ExecX(ctx context.Context) {
	if err := srcb.Exec(ctx); err != nil {
		panic(err)
	}
}
