// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package server

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"
	"zero-admin/apps/admin/rpc/internal/logic/role"
	"zero-admin/apps/admin/rpc/internal/svc"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServer) AddRole(ctx context.Context, in *admin.AddRoleReq) (*admin.AddRoleResp, error) {
	l := rolelogic.NewAddRoleLogic(ctx, s.svcCtx)
	return l.AddRole(in)
}

func (s *RoleServer) DeleteRole(ctx context.Context, in *admin.DeleteRoleReq) (*admin.DeleteRoleResp, error) {
	l := rolelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *RoleServer) UpdateRole(ctx context.Context, in *admin.UpdateRoleReq) (*admin.UpdateRoleResp, error) {
	l := rolelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *RoleServer) RoleList(ctx context.Context, in *admin.RoleListReq) (*admin.RoleListResp, error) {
	l := rolelogic.NewRoleListLogic(ctx, s.svcCtx)
	return l.RoleList(in)
}
