// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package menu

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq      = admin.AddMenuReq
	AddMenuResp     = admin.AddMenuResp
	AddRoleReq      = admin.AddRoleReq
	AddRoleResp     = admin.AddRoleResp
	AddUserReq      = admin.AddUserReq
	AddUserResp     = admin.AddUserResp
	CasbinCheckReq  = admin.CasbinCheckReq
	CasbinCheckResp = admin.CasbinCheckResp
	DeleteMenuReq   = admin.DeleteMenuReq
	DeleteMenuResp  = admin.DeleteMenuResp
	DeleteRoleReq   = admin.DeleteRoleReq
	DeleteRoleResp  = admin.DeleteRoleResp
	DeleteUserReq   = admin.DeleteUserReq
	DeleteUserResp  = admin.DeleteUserResp
	GetMenuReq      = admin.GetMenuReq
	GetMenuResp     = admin.GetMenuResp
	LoginReq        = admin.LoginReq
	LoginResp       = admin.LoginResp
	MenuData        = admin.MenuData
	MenuListReq     = admin.MenuListReq
	MenuListResp    = admin.MenuListResp
	RefreshReq      = admin.RefreshReq
	RoleData        = admin.RoleData
	RoleListReq     = admin.RoleListReq
	RoleListResp    = admin.RoleListResp
	UpdateMenuReq   = admin.UpdateMenuReq
	UpdateMenuResp  = admin.UpdateMenuResp
	UpdateRoleReq   = admin.UpdateRoleReq
	UpdateRoleResp  = admin.UpdateRoleResp
	UpdateUserReq   = admin.UpdateUserReq
	UpdateUserResp  = admin.UpdateUserResp
	UserData        = admin.UserData
	UserListReq     = admin.UserListReq
	UserListResp    = admin.UserListResp

	Menu interface {
		AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error)
		MenuList(ctx context.Context, in *MenuListReq, opts ...grpc.CallOption) (*MenuListResp, error)
		GetMenu(ctx context.Context, in *GetMenuReq, opts ...grpc.CallOption) (*GetMenuResp, error)
	}

	defaultMenu struct {
		cli zrpc.Client
	}
)

func NewMenu(cli zrpc.Client) Menu {
	return &defaultMenu{
		cli: cli,
	}
}

func (m *defaultMenu) AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error) {
	client := admin.NewMenuClient(m.cli.Conn())
	return client.AddMenu(ctx, in, opts...)
}

func (m *defaultMenu) DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error) {
	client := admin.NewMenuClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultMenu) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error) {
	client := admin.NewMenuClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultMenu) MenuList(ctx context.Context, in *MenuListReq, opts ...grpc.CallOption) (*MenuListResp, error) {
	client := admin.NewMenuClient(m.cli.Conn())
	return client.MenuList(ctx, in, opts...)
}

func (m *defaultMenu) GetMenu(ctx context.Context, in *GetMenuReq, opts ...grpc.CallOption) (*GetMenuResp, error) {
	client := admin.NewMenuClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}
