// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	attrNameFieldNames          = builder.RawFieldNames(&AttrName{})
	attrNameRows                = strings.Join(attrNameFieldNames, ",")
	attrNameRowsExpectAutoSet   = strings.Join(stringx.Remove(attrNameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	attrNameRowsWithPlaceHolder = strings.Join(stringx.Remove(attrNameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	attrNameModel interface {
		Insert(ctx context.Context, data *AttrName) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AttrName, error)
		Update(ctx context.Context, data *AttrName) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAttrNameModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AttrName struct {
		Id         int64     `db:"id"`   // 属性值ID
		Name       string    `db:"name"` // 属性值
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newAttrNameModel(conn sqlx.SqlConn) *defaultAttrNameModel {
	return &defaultAttrNameModel{
		conn:  conn,
		table: "`attr_name`",
	}
}

func (m *defaultAttrNameModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAttrNameModel) FindOne(ctx context.Context, id int64) (*AttrName, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", attrNameRows, m.table)
	var resp AttrName
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAttrNameModel) Insert(ctx context.Context, data *AttrName) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, attrNameRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name)
	return ret, err
}

func (m *defaultAttrNameModel) Update(ctx context.Context, data *AttrName) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, attrNameRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Id)
	return err
}

func (m *defaultAttrNameModel) tableName() string {
	return m.table
}
