// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	businessFieldNames          = builder.RawFieldNames(&Business{})
	businessRows                = strings.Join(businessFieldNames, ",")
	businessRowsExpectAutoSet   = strings.Join(stringx.Remove(businessFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	businessRowsWithPlaceHolder = strings.Join(stringx.Remove(businessFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBusinessIdPrefix      = "cache:business:id:"
	cacheBusinessAdminIdPrefix = "cache:business:adminId:"
	cacheBusinessPhonePrefix   = "cache:business:phone:"
)

type (
	businessModel interface {
		Insert(ctx context.Context, data *Business) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Business, error)
		FindOneByAdminId(ctx context.Context, adminId int64) (*Business, error)
		FindOneByPhone(ctx context.Context, phone string) (*Business, error)
		Update(ctx context.Context, data *Business) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBusinessModel struct {
		sqlc.CachedConn
		table string
	}

	Business struct {
		Id         int64     `db:"id"`       // 商家ID
		Phone      string    `db:"phone"`    // 手机号
		TgId       string    `db:"tg_id"`    // TG ID
		AdminId    int64     `db:"admin_id"` // 管理后台ID
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newBusinessModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBusinessModel {
	return &defaultBusinessModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`business`",
	}
}

func (m *defaultBusinessModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	businessAdminIdKey := fmt.Sprintf("%s%v", cacheBusinessAdminIdPrefix, data.AdminId)
	businessIdKey := fmt.Sprintf("%s%v", cacheBusinessIdPrefix, id)
	businessPhoneKey := fmt.Sprintf("%s%v", cacheBusinessPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, businessAdminIdKey, businessIdKey, businessPhoneKey)
	return err
}

func (m *defaultBusinessModel) FindOne(ctx context.Context, id int64) (*Business, error) {
	businessIdKey := fmt.Sprintf("%s%v", cacheBusinessIdPrefix, id)
	var resp Business
	err := m.QueryRowCtx(ctx, &resp, businessIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", businessRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBusinessModel) FindOneByAdminId(ctx context.Context, adminId int64) (*Business, error) {
	businessAdminIdKey := fmt.Sprintf("%s%v", cacheBusinessAdminIdPrefix, adminId)
	var resp Business
	err := m.QueryRowIndexCtx(ctx, &resp, businessAdminIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `admin_id` = ? limit 1", businessRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, adminId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBusinessModel) FindOneByPhone(ctx context.Context, phone string) (*Business, error) {
	businessPhoneKey := fmt.Sprintf("%s%v", cacheBusinessPhonePrefix, phone)
	var resp Business
	err := m.QueryRowIndexCtx(ctx, &resp, businessPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", businessRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBusinessModel) Insert(ctx context.Context, data *Business) (sql.Result, error) {
	businessAdminIdKey := fmt.Sprintf("%s%v", cacheBusinessAdminIdPrefix, data.AdminId)
	businessIdKey := fmt.Sprintf("%s%v", cacheBusinessIdPrefix, data.Id)
	businessPhoneKey := fmt.Sprintf("%s%v", cacheBusinessPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, businessRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.TgId, data.AdminId)
	}, businessAdminIdKey, businessIdKey, businessPhoneKey)
	return ret, err
}

func (m *defaultBusinessModel) Update(ctx context.Context, newData *Business) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	businessAdminIdKey := fmt.Sprintf("%s%v", cacheBusinessAdminIdPrefix, data.AdminId)
	businessIdKey := fmt.Sprintf("%s%v", cacheBusinessIdPrefix, data.Id)
	businessPhoneKey := fmt.Sprintf("%s%v", cacheBusinessPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, businessRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Phone, newData.TgId, newData.AdminId, newData.Id)
	}, businessAdminIdKey, businessIdKey, businessPhoneKey)
	return err
}

func (m *defaultBusinessModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBusinessIdPrefix, primary)
}

func (m *defaultBusinessModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", businessRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBusinessModel) tableName() string {
	return m.table
}
