// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	skuFieldNames          = builder.RawFieldNames(&Sku{})
	skuRows                = strings.Join(skuFieldNames, ",")
	skuRowsExpectAutoSet   = strings.Join(stringx.Remove(skuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	skuRowsWithPlaceHolder = strings.Join(stringx.Remove(skuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSkuIdPrefix = "cache:sku:id:"
)

type (
	skuModel interface {
		Insert(ctx context.Context, data *Sku) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Sku, error)
		Update(ctx context.Context, data *Sku) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSkuModel struct {
		sqlc.CachedConn
		table string
	}

	Sku struct {
		Id         int64     `db:"id"`         // SKU ID
		ProductId  int64     `db:"product_id"` // 商品ID
		Price      float64   `db:"price"`      // 价格
		Stock      int64     `db:"stock"`      // 库存
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newSkuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSkuModel {
	return &defaultSkuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sku`",
	}
}

func (m *defaultSkuModel) Delete(ctx context.Context, id int64) error {
	skuIdKey := fmt.Sprintf("%s%v", cacheSkuIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, skuIdKey)
	return err
}

func (m *defaultSkuModel) FindOne(ctx context.Context, id int64) (*Sku, error) {
	skuIdKey := fmt.Sprintf("%s%v", cacheSkuIdPrefix, id)
	var resp Sku
	err := m.QueryRowCtx(ctx, &resp, skuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", skuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkuModel) Insert(ctx context.Context, data *Sku) (sql.Result, error) {
	skuIdKey := fmt.Sprintf("%s%v", cacheSkuIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, skuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Price, data.Stock)
	}, skuIdKey)
	return ret, err
}

func (m *defaultSkuModel) Update(ctx context.Context, data *Sku) error {
	skuIdKey := fmt.Sprintf("%s%v", cacheSkuIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, skuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Price, data.Stock, data.Id)
	}, skuIdKey)
	return err
}

func (m *defaultSkuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSkuIdPrefix, primary)
}

func (m *defaultSkuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", skuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSkuModel) tableName() string {
	return m.table
}
