// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: merchant.proto

package server

import (
	"context"

	"xlife/apps/merchant/rpc/merchant"
	"xlife/apps/merchant/rpc/internal/logic"
	"xlife/apps/merchant/rpc/internal/svc"
)

type BusinessServer struct {
	svcCtx *svc.ServiceContext
	merchant.UnimplementedBusinessServer
}

func NewBusinessServer(svcCtx *svc.ServiceContext) *BusinessServer {
	return &BusinessServer{
		svcCtx: svcCtx,
	}
}

func (s *BusinessServer) AddBusiness(ctx context.Context, in *merchant.AddBusinessReq) (*merchant.BusinessInfo, error) {
	l := logic.NewAddBusinessLogic(ctx, s.svcCtx)
	return l.AddBusiness(in)
}

func (s *BusinessServer) UpdateBusiness(ctx context.Context, in *merchant.BusinessInfo) (*merchant.BusinessInfo, error) {
	l := logic.NewUpdateBusinessLogic(ctx, s.svcCtx)
	return l.UpdateBusiness(in)
}

func (s *BusinessServer) DeleteBusiness(ctx context.Context, in *merchant.DeleteBusinessReq) (*merchant.DeleteBusinessResp, error) {
	l := logic.NewDeleteBusinessLogic(ctx, s.svcCtx)
	return l.DeleteBusiness(in)
}

func (s *BusinessServer) GetBusiness(ctx context.Context, in *merchant.GetBusinessReq) (*merchant.GetBusinessResp, error) {
	l := logic.NewGetBusinessLogic(ctx, s.svcCtx)
	return l.GetBusiness(in)
}
