// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package server

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"
	"zero-admin/apps/admin/rpc/internal/logic/menu"
	"zero-admin/apps/admin/rpc/internal/svc"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServer) AddMenu(ctx context.Context, in *admin.AddMenuReq) (*admin.AddMenuResp, error) {
	l := menulogic.NewAddMenuLogic(ctx, s.svcCtx)
	return l.AddMenu(in)
}

func (s *MenuServer) DeleteMenu(ctx context.Context, in *admin.DeleteMenuReq) (*admin.DeleteMenuResp, error) {
	l := menulogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *MenuServer) UpdateMenu(ctx context.Context, in *admin.UpdateMenuReq) (*admin.UpdateMenuResp, error) {
	l := menulogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *MenuServer) GetMenu(ctx context.Context, in *admin.GetMenuReq) (*admin.GetMenuResp, error) {
	l := menulogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}
