CREATE TABLE
    cate (
        id INT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '分类ID',
        store_id INT NOT NULL COMMENT '店铺ID',
        name VARCHAR(255) NOT NULL COMMENT '分类名称',
        sort INT NOT NULL DEFAULT 0 COMMENT '排序',
        create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    ) COMMENT '分类表';