CREATE TABLE
    sku (
        id INT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'SKU ID',
        product_id INT NOT NULL COMMENT '商品ID',
        price DECIMAL(10, 2) NOT NULL COMMENT '价格',
        stock INT NOT NULL COMMENT '库存',
        create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    ) COMMENT 'SKU表';