CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    creator BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '用户角色关联表';