CREATE TABLE IF NOT EXISTS sys_role_menu (
    role_id BIGINT NOT NULL COMMENT '角色ID',
    menu_id BIGINT NOT NULL COMMENT '菜单ID',
    creator BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
    updater BIGINT NOT NULL DEFAULT 0 COMMENT '修改人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '角色菜单关联表';