CREATE TABLE IF NOT EXISTS sys_department (
    id BIGINT AUTO_INCREMENT COMMENT '部门ID',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父ID',
    name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '名称',
    sort TINYINT NOT NULL DEFAULT 0 COMMENT '排序',
    remark VARCHAR(512) NOT NULL DEFAULT '' COMMENT '备注',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态(0:启用,1:禁用)',
    creator BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
    updater BIGINT NOT NULL DEFAULT 0 COMMENT '修改人',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id)
) COMMENT '部门表';