// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package server

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"
	"zero-admin/apps/admin/rpc/internal/logic/casbin"
	"zero-admin/apps/admin/rpc/internal/svc"
)

type CasbinServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedCasbinServer
}

func NewCasbinServer(svcCtx *svc.ServiceContext) *CasbinServer {
	return &CasbinServer{
		svcCtx: svcCtx,
	}
}

func (s *CasbinServer) Check(ctx context.Context, in *admin.CasbinCheckReq) (*admin.CasbinCheckResp, error) {
	l := casbinlogic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
