// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: admin.proto

package admin_client

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMenuReq     = admin.AddMenuReq
	AddMenuResp    = admin.AddMenuResp
	AddUserReq     = admin.AddUserReq
	AddUserResp    = admin.AddUserResp
	DeleteMenuReq  = admin.DeleteMenuReq
	DeleteMenuResp = admin.DeleteMenuResp
	DeleteUserReq  = admin.DeleteUserReq
	DeleteUserResp = admin.DeleteUserResp
	GetMenuReq     = admin.GetMenuReq
	GetMenuResp    = admin.GetMenuResp
	GetUserReq     = admin.GetUserReq
	GetUserResp    = admin.GetUserResp
	LoginReq       = admin.LoginReq
	LoginResp      = admin.LoginResp
	MenuData       = admin.MenuData
	RefreshReq     = admin.RefreshReq
	UpdateMenuReq  = admin.UpdateMenuReq
	UpdateMenuResp = admin.UpdateMenuResp
	UpdateUserReq  = admin.UpdateUserReq
	UpdateUserResp = admin.UpdateUserResp
	UserData       = admin.UserData

	Admin interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*LoginResp, error)
		AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserReq, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error)
		GetMenu(ctx context.Context, in *GetMenuReq, opts ...grpc.CallOption) (*GetMenuResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAdmin) Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultAdmin) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserReq, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultAdmin) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultAdmin) AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AddMenu(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultAdmin) GetMenu(ctx context.Context, in *GetMenuReq, opts ...grpc.CallOption) (*GetMenuResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}
