// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package admin_client

import (
	"context"

	"zero-admin/apps/admin/rpc/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserReq     = admin.AddUserReq
	AddUserResp    = admin.AddUserResp
	DeleteUserReq  = admin.DeleteUserReq
	DeleteUserResp = admin.DeleteUserResp
	GetUserReq     = admin.GetUserReq
	GetUserResp    = admin.GetUserResp
	LoginReq       = admin.LoginReq
	LoginResp      = admin.LoginResp
	RefreshReq     = admin.RefreshReq
	UpdateUserReq  = admin.UpdateUserReq
	UpdateUserResp = admin.UpdateUserResp
	UserData       = admin.UserData

	Admin interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*LoginResp, error)
		AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAdmin) Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultAdmin) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultAdmin) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
